image: ubuntu

stages:
  - pages

before_script:
  - echo "Acquire::http::Proxy \"http://apt.dmz.qb:3142\";" > /etc/apt/apt.conf.d/00proxy
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get -y install git python3-dev python3-pip wget pkg-config build-essential cmake make libmysqlclient-dev mysql-client
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8

pages:
  stage: pages
  script:
    # Installing some deps
    - pip3 install -U setuptools
    - pip3 install -r doc/requirements.txt

    # Generate html doc
    - cd doc && make html && cd ..
    - mv doc/_build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
  variables:
    READTHEDOCS: "True"
